import { describe, expect, it } from "vitest";
import { checkers, parseBoard, type CheckersState } from "./engine";
import { suggestCheckers } from "./ai";

const idx = (r: number, c: number) => r * 8 + c;
const state = (d: string, current: "A" | "B" = "A"): CheckersState => ({
  board: parseBoard(d),
  current,
  noProgress: 0,
  last: null,
});

describe("Damas: pistas", () => {
  it("sugiere una jugada legal desde la apertura, con razón", () => {
    const s = checkers.initialState("A");
    const h = suggestCheckers(s)!;
    expect(checkers.isLegal(s, h.move)).toBe(true);
    expect(h.reason.length).toBeGreaterThan(5);
  });

  it("prefiere la captura doble sobre la simple cuando hay opción", () => {
    const s = state(`
      ........
      ........
      ........
      ....b...
      ........
      ..b...b.
      .a...a..
      ........
    `);
    const h = suggestCheckers(s)!;
    expect(h.move.path).toEqual([idx(6, 1), idx(4, 3), idx(2, 5)]);
    expect(h.reason).toMatch(/2 piezas/);
  });

  it("evita regalar una pieza cuando hay una jugada segura", () => {
    // El peón de (5,2) puede ir a (4,1) seguro o a (4,3) donde lo capturan.
    const s = state(`
      ........
      ........
      ....b...
      ........
      ........
      ..a.....
      ........
      a.......
    `);
    const h = suggestCheckers(s)!;
    const safe = [idx(5, 2), idx(4, 1)];
    const alsoSafe = [idx(7, 0), idx(6, 1)];
    expect([safe, alsoSafe]).toContainEqual(h.move.path);
  });

  it("devuelve null si la partida terminó", () => {
    const s = state(`
      ........
      ........
      ........
      ........
      ...a....
      ........
      ........
      ........
    `, "B");
    expect(suggestCheckers(s)).toBeNull();
  });
});
