import { describe, expect, it } from "vitest";
import {
  checkers,
  countPieces,
  DRAW_AFTER_PLIES,
  isDark,
  parseBoard,
  type CheckersState,
} from "./engine";

const idx = (r: number, c: number) => r * 8 + c;

function state(
  diagram: string,
  current: "A" | "B" = "A",
  noProgress = 0,
): CheckersState {
  return { board: parseBoard(diagram), current, noProgress, last: null };
}

const paths = (s: CheckersState) =>
  checkers
    .legalMoves(s)
    .map((m) => m.path)
    .sort((a, b) => a.join(",").localeCompare(b.join(",")));

describe("Damas: posición inicial", () => {
  it("coloca 12 piezas por lado solo en casillas oscuras", () => {
    const s = checkers.initialState("A");
    expect(countPieces(s.board, "A")).toBe(12);
    expect(countPieces(s.board, "B")).toBe(12);
    s.board.forEach((p, i) => {
      if (p) expect(isDark(i)).toBe(true);
    });
    // A abajo (filas 5-7), B arriba (filas 0-2)
    expect(s.board[idx(7, 0)]).toBe("a");
    expect(s.board[idx(0, 1)]).toBe("b");
    expect(s.board[idx(3, 0)]).toBeNull();
  });

  it("el primer jugador tiene 7 aperturas posibles", () => {
    expect(checkers.legalMoves(checkers.initialState("A"))).toHaveLength(7);
    expect(checkers.legalMoves(checkers.initialState("B"))).toHaveLength(7);
  });
});

describe("Damas: movimientos simples", () => {
  it("un peón avanza una casilla en diagonal, nunca hacia atrás", () => {
    const s = state(`
      ........
      ........
      ........
      ........
      ...a....
      ........
      ........
      .b......
    `);
    expect(paths(s)).toEqual([
      [idx(4, 3), idx(3, 2)],
      [idx(4, 3), idx(3, 4)],
    ]);
  });

  it("una dama se mueve en las cuatro diagonales, una casilla", () => {
    const s = state(`
      ........
      ........
      ........
      ........
      ...A....
      ........
      ........
      .b......
    `);
    expect(paths(s)).toHaveLength(4);
    expect(paths(s)).toContainEqual([idx(4, 3), idx(5, 4)]);
  });
});

describe("Damas: capturas", () => {
  it("la captura es obligatoria y excluye los movimientos simples", () => {
    const s = state(`
      ........
      ........
      ........
      ....b...
      ...a....
      ........
      .a......
      ........
    `);
    expect(paths(s)).toEqual([[idx(4, 3), idx(2, 5)]]);
  });

  it("obliga a completar la cadena de saltos", () => {
    const s = state(`
      ........
      ........
      ........
      ....b...
      ........
      ..b.....
      .a......
      ........
    `);
    const full = [idx(6, 1), idx(4, 3), idx(2, 5)];
    expect(paths(s)).toEqual([full]);
    expect(checkers.isLegal(s, { path: [idx(6, 1), idx(4, 3)] })).toBe(false);
    expect(
      checkers.explainIllegal(s, { path: [idx(6, 1), idx(4, 3)] }),
    ).toMatch(/Sigue saltando/);

    const next = checkers.applyMove(s, { path: full });
    expect(countPieces(next.board, "B")).toBe(0);
    expect(next.board[idx(2, 5)]).toBe("a");
    expect(next.last).toEqual({ path: full, captured: [idx(5, 2), idx(3, 4)] });
  });

  it("un peón no captura hacia atrás", () => {
    const s = state(`
      ........
      ........
      ........
      ........
      ...a....
      ....b...
      ........
      ........
    `);
    // Solo avanza; la pieza de atrás no se puede saltar.
    expect(paths(s)).toEqual([
      [idx(4, 3), idx(3, 2)],
      [idx(4, 3), idx(3, 4)],
    ]);
  });

  it("una dama captura en cualquier dirección y encadena saltos", () => {
    const s = state(`
      ........
      ........
      ........
      ........
      ...A....
      ....b.b.
      ........
      ........
    `);
    expect(paths(s)).toEqual([[idx(4, 3), idx(6, 5), idx(4, 7)]]);
  });
});

describe("Damas: coronación", () => {
  it("al llegar al fondo se convierte en dama y termina el turno", () => {
    const s = state(`
      ........
      ..b.b...
      .a......
      ........
      ........
      ........
      ........
      ........
    `);
    // Tras coronar en (0,3) podría seguir saltando a (2,5), pero no se permite.
    expect(paths(s)).toEqual([[idx(2, 1), idx(0, 3)]]);
    const next = checkers.applyMove(s, { path: [idx(2, 1), idx(0, 3)] });
    expect(next.board[idx(0, 3)]).toBe("A");
    expect(next.board[idx(1, 2)]).toBeNull();
    expect(next.board[idx(1, 4)]).toBe("b");
  });

  it("B corona en la fila 7", () => {
    const s = state(
      `
      ........
      ........
      ........
      ........
      ........
      ........
      ..b.....
      ...a....
    `,
      "B",
    );
    const next = checkers.applyMove(s, { path: [idx(6, 2), idx(7, 1)] });
    expect(next.board[idx(7, 1)]).toBe("B");
  });
});

describe("Damas: fin de partida", () => {
  it("gana quien deja al otro sin piezas", () => {
    const s = state(`
      ........
      ........
      ........
      ........
      ...a....
      ........
      ........
      ........
    `, "B");
    expect(checkers.status(s)).toEqual({ kind: "win", winner: "A" });
    expect(checkers.legalMoves(s)).toHaveLength(0);
  });

  it("gana quien deja al otro bloqueado", () => {
    const s = state(`
      ........
      ........
      ........
      ........
      ........
      ..b.....
      .b......
      a.......
    `);
    expect(checkers.status(s)).toEqual({ kind: "win", winner: "B" });
  });

  it("es tablas tras muchas jugadas sin progreso", () => {
    const s = state(`
      .B......
      ........
      ........
      ........
      ...A....
      ........
      ........
      ........
    `, "A", DRAW_AFTER_PLIES - 1);
    expect(checkers.status(s).kind).toBe("playing");
    const next = checkers.applyMove(s, { path: [idx(4, 3), idx(3, 2)] });
    expect(next.noProgress).toBe(DRAW_AFTER_PLIES);
    expect(checkers.status(next)).toEqual({ kind: "draw" });
  });

  it("mover un peón o capturar reinicia el contador de progreso", () => {
    const s = state(`
      .B......
      ........
      ........
      ........
      ...a....
      ........
      ........
      ........
    `, "A", 30);
    const next = checkers.applyMove(s, { path: [idx(4, 3), idx(3, 2)] });
    expect(next.noProgress).toBe(0);
  });
});

describe("Damas: explicaciones", () => {
  const s = state(`
    ........
    ........
    ........
    ..b.....
    ...a....
    ........
    ..a.....
    b.......
  `);

  it("explica casilla ocupada, casilla clara y retroceso", () => {
    expect(checkers.explainIllegal(s, { path: [idx(4, 3), idx(3, 3)] })).toMatch(/oscuras/);
    expect(checkers.explainIllegal(s, { path: [idx(4, 3), idx(3, 2)] })).toMatch(/ocupada/);
    expect(checkers.explainIllegal(s, { path: [idx(4, 3), idx(5, 4)] })).toMatch(/hacia adelante/);
  });

  it("explica pieza ajena y casilla vacía", () => {
    expect(checkers.explainIllegal(s, { path: [idx(7, 0), idx(6, 1)] })).toMatch(/no es tuya/);
    expect(checkers.explainIllegal(s, { path: [idx(2, 1)] })).toMatch(/ninguna pieza/);
  });

  it("explica la captura obligatoria", () => {
    const c = state(`
      ........
      ........
      ........
      ....b...
      ...a....
      ........
      .a......
      ........
    `);
    expect(checkers.explainIllegal(c, { path: [idx(6, 1), idx(5, 0)] })).toMatch(/obligatoria/);
    expect(checkers.explainIllegal(c, { path: [idx(4, 3), idx(3, 2)] })).toMatch(/obligatoria/);
  });

  it("rechaza formas inválidas sin lanzar", () => {
    expect(checkers.isLegal(s, { path: [] })).toBe(false);
    expect(checkers.isLegal(s, { path: [99, 3] })).toBe(false);
    expect(checkers.isLegal(s, null as never)).toBe(false);
  });
});

describe("Damas: inmutabilidad", () => {
  it("applyMove no modifica el estado anterior", () => {
    const s0 = checkers.initialState("A");
    const m = checkers.legalMoves(s0)[0];
    const s1 = checkers.applyMove(s0, m);
    expect(s0.board[m.path[0]]).toBe("a");
    expect(s1.board[m.path[0]]).toBeNull();
    expect(s1.current).toBe("B");
  });
});
